In [2]:
import pandas as pd
df = pd.read_csv("data_cleaning.csv")

In [3]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [5]:
df.sort_values("Age")

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [6]:
import pandas as pd
 
# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}
 
df = pd.DataFrame(data)
 
# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [7]:
df.melt(id_vars=None, value_vars=None, var_name=None, value_name="value", col_level=None)

   variable    value
0      Name    Alice
1      Name      Bob
2      Name  Charlie
3      Math       85
4      Math       78
5      Math       92
6   Science       90
7   Science       82
8   Science       89
9   English       88
10  English       85
11  English       94