In [1]:
import pandas as pd

In [2]:
data = [['harry', 34],['mussu',44], ['muskan',99]]

In [3]:
data

[['harry', 34], ['mussu', 44], ['muskan', 99]]

In [4]:
pd.DataFrame(data, columns = ["Name", "Marks"])

     Name  Marks
0   harry     34
1   mussu     44
2  muskan     99

In [5]:
df = pd.read_excel("data.xlsx")

In [6]:
df

Empty DataFrame
Columns: []
Index: []

In [7]:
import os
os.listdir()

['.ipynb_checkpoints',
 '.virtual_documents',
 'creating df.ipynb',
 'data.xlsx',
 'dataanalysis.ipynb',
 'pandas.ipynb']

In [8]:
import pandas as pd

df = pd.read_excel("data.xlsx")
df

Empty DataFrame
Columns: []
Index: []

In [9]:
df.head()

Empty DataFrame
Columns: []
Index: []

In [10]:
import pandas as pd

df = pd.read_excel("data.xlsx")

print(df)

Empty DataFrame
Columns: []
Index: []

In [11]:
df.shape

(0, 0)

In [12]:
import pandas as pd

df = pd.read_excel("data.xlsx", sheet_name="Sheet1")
print(df)

Empty DataFrame
Columns: []
Index: []

In [13]:
import pandas as pd

xls = pd.ExcelFile("data.xlsx")
print(xls.sheet_names)

['Sheet1']

In [19]:
df = pd.read_excel("data2.xlsx")

In [20]:
df

   name  school  marks
0     a       1     88
1     b       2     77
2     c       3     66
3     d       4     55
4     e       5     44
5     f       6     33
6     g       7     22
7     h       8     11

In [21]:
print(df)

   name  school  marks
0     a       1     88
1     b       2     77
2     c       3     66
3     d       4     55
4     e       5     44
5     f       6     33
6     g       7     22
7     h       8     11